#!/bin/sh
LEVEL0_DOCROOT=../www
source "$(dirname "$0")/transifex_config"

for lang in *.mo
do
	MPATH=$LEVEL0_DOCROOT/locale/`basename $lang .mo`/LC_MESSAGES
	mkdir -p $MPATH
	cp $lang $MPATH/messages.mo
done
