#!/bin/sh

# Do not, I repeat, ***DO NOT*** leave here your Transifex credentials when pushing the file to github!
TRANSIFEX_USER=
TRANSIFEX_PASS=

LEVEL0_LANGS=`curl https://www.transifex.com/api/2/project/level0/resource/messages/?details --user "$TRANSIFEX_USER:$TRANSIFEX_PASS" -s|grep '"code"'|sed 's/^.\+": "\(.\+\)".*$/\1/'`

for lang in $LEVEL0_LANGS
do
	echo "Processing language $lang"
	curl https://www.transifex.com/api/2/project/level0/resource/messages/translation/ru --user 'Zverik:EldoSim5' -s|grep content|sed 's/^.\+": "\(.\+\)",\s*$/\1/'|sed 's/\\\\n/%NEWLINE%/g'|sed 's/\\n/\n/g'|sed 's/\\$//mg' |sed 's/%NEWLINE%/\\n/g' |sed 's/\\"/"/g'|sed 's/\\\\/\\/g'|msgfmt -o $lang.mo -
done
