#!/bin/sh
set -u

CONFIG="$(dirname "$0")/transifex_config"
if [ -e "$CONFIG" ]; then
  source "$CONFIG"
else
  echo "Please enter your Transifex credentials"
  read -r -p "Login: " TRANSIFEX_USER
  read -r -s -p "Password: " TRANSIFEX_PASS
  CHECK="$(curl -w "%{http_code}" -o /dev/null -s 'https://www.transifex.com/api/2/projects' --user "$TRANSIFEX_USER:$TRANSIFEX_PASS")"
  [ "$CHECK" -ne "200" ] && echo "Wrong login or password, please try again." && exit 3
  echo "TRANSIFEX_USER=$TRANSIFEX_USER" > "$CONFIG"
  echo "TRANSIFEX_PASS=$TRANSIFEX_PASS" > "$CONFIG"
fi

LEVEL0_LANGS=`curl https://www.transifex.com/api/2/project/level0/resource/messages/?details --user "$TRANSIFEX_USER:$TRANSIFEX_PASS" -s|grep '"code"'|sed 's/^.\+": "\(.\+\)".*$/\1/'`

for lang in $LEVEL0_LANGS
do
	echo "Processing language $lang"
	curl https://www.transifex.com/api/2/project/level0/resource/messages/translation/$lang --user "$TRANSIFEX_USER:$TRANSIFEX_PASS" -s|grep content|sed 's/^.\+": "\(.\+\)",\s*$/\1/'|sed 's/\\\\n/%NEWLINE%/g'|sed 's/\\n/\n/g'|sed 's/\\$//mg' |sed 's/%NEWLINE%/\\n/g' |sed 's/\\"/"/g'|sed 's/\\\\/\\/g'|msgfmt -o $lang.mo -
done
