name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # https://www.php.net/supported-versions.php
        php-version: ['8.3']

    name: Level0 tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: Run tests
        run: |
          composer validate
          ./vendor/bin/phpunit --display-warnings test/
